name: "Build"
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm run build
      - uses: EndBug/add-and-commit@v4
        with:
          add: lib
          message: "[auto] build: update build"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
